# Generated by Django 5.2.6 on 2025-10-04 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tier',
            field=models.CharField(choices=[('standard', 'Standard'), ('Free', 'free')], default='free', max_length=20),
        ),
    ]
