# Generated by Django 5.2.6 on 2025-09-29 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_delete_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
