# Generated by Django 5.2.6 on 2025-10-04 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_article_tier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
    ]
