# Generated by Django 5.2.6 on 2025-10-04 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_remove_article_keywords_remove_article_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tier',
            field=models.CharField(choices=[('standard', 'Standard'), ('Free', 'free')], max_length=20),
        ),
    ]
