# Generated by Django 5.2.6 on 2025-10-04 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_article_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tier',
            field=models.CharField(choices=[('standard', 'Standard'), ('free', 'Free')], max_length=20),
        ),
    ]
