# Generated by Django 5.2.6 on 2025-10-04 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_payment_payment_method_payment_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='tier',
            field=models.CharField(choices=[('standard', 'Standard')], default='free', max_length=20),
        ),
    ]
