# Generated by Django 5.2.6 on 2025-10-04 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_alter_subscription_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='tier',
            field=models.CharField(choices=[('standard', 'Standard'), ('Free', 'free')], default='free', max_length=20),
        ),
    ]
